Added Flexbox and modified FormComponent
web-slate/TwixtUI pull request #24
Opened 2024-06-20 17:06 UTC by Sruthi-273

@ramsunvtech @prvn-mhsh

2024-06-20 23:22 UTC, ramsunvtech requested changes

2024-06-20 23:22 UTC, ramsunvtech commented on react/src/FormComponent.js
> +    />
why are we hard coding input text element instead of single line iinput component?

2024-06-20 23:22 UTC, ramsunvtech commented on react/src/FormComponent.js
> +const FormField = ({ id, label }) => (
this is SingleLineInputField

2024-06-20 23:22 UTC, ramsunvtech commented on react/src/FormComponent.js
> +      ))}
As a first step, prop driven Form field looks good to me.

next step should work like below.

<TwixtSimpleForm>
    <TwixtSimpleForm.SingleLineInput />
    <TwixtSimpleForm.SingleSelectionDrpdown />
    <TwixtSimpleForm.MultipleSelectionDrpdown />
    <TwixtSimpleForm.Field5 />
    <TwixtSimpleForm.Field6 />
    <TwixtSimpleForm.SubmitButton />
    <TwixtSimpleForm.ResetButton />
    <TwixtSimpleForm.AdditionalButton />
</TwixtSimpleForm>

2024-06-20 23:22 UTC, ramsunvtech commented on react/src/index.js
> +export { default as Flexbox } from './Flexbox';
even FlexBox can be separate component like


```
TwixtFlexbox
```

2024-08-22 03:56 UTC, prvn-mhsh commented
Not in proper alignment

2024-08-22 03:56 UTC, closed without merging