feat(communications): add badge component
web-slate/TwixtUI pull request #78
Opened 2024-08-29 05:05 UTC by yuvarajuv

![image](https://github.com/user-attachments/assets/c5fc8dac-b4a6-495d-9cce-fc6d6f54291c)

2024-09-04 15:58 UTC, send2alamelu commented
@yuvarajuv, can this left and right icon section similar to button

2024-09-08 05:38 UTC, yuvarajuv commented
> @yuvarajuv, can this left and right icon section similar to button

@send2alamelu Added left and right icon section

2024-09-08 06:08 UTC, send2alamelu requested changes

2024-09-08 06:08 UTC, send2alamelu commented on react/src/Communications/Badge/Badge.js
> +    <div className={badgeClasses}>
can u replace BoxItem for div and span and use overwrite class ?

2024-09-08 06:09 UTC, send2alamelu requested changes

2024-09-08 06:09 UTC, send2alamelu commented on react-examples/stories/Communications/Badge.stories.js
> +  status: 'Warning',
status value should be in lower case

2024-09-08 06:10 UTC, send2alamelu commented on react-examples/stories/Communications/Badge.stories.js
> +  leftIcon: <TwixtIcon type="user" variant="filled" size="16" color="color" />,
color should not be color

2024-09-08 06:33 UTC, send2alamelu commented
@yuvarajuv, can u move the current badge and its stories to 

_deprecated directory

and change the stories as

stories\Badges.stories.js

```
title: 'Common/TwixtBadges',
component: TwixtBadges_DEPRECATED,
```

2024-09-08 10:44 UTC, send2alamelu approved these changes
LGTM

2024-09-08 10:44 UTC, merged