Copy link component
web-slate/TwixtUI pull request #81
Opened 2024-09-01 07:48 UTC by adhiththiyan

![Screenshot 2024-09-01 124943](https://github.com/user-attachments/assets/f32ffc43-20cc-44b6-98eb-86179bc6a857)

2024-09-01 07:56 UTC, alameluvenkat requested changes

2024-09-01 07:56 UTC, alameluvenkat commented on react/src/CallsToAction/CopyLink/CopyLink.js
> +  const handleCopyClick = async (e)=>{
format the code

2024-09-01 07:56 UTC, alameluvenkat commented on react/src/index.js
> +export { default as TwixtToolTip_DEPRECATED } from './_deprecated/Tooltip';
add current copy link as deprecated and move this to deprectaed directory

2024-09-01 10:57 UTC, send2alamelu commented on react/src/CallsToAction/CopyLink/CopyLink.js
> +        <div className='absolute bottom-full mb-2 text-sm text-white bg-green-500 rounded px-2 py-1'>
use tooltip component instead of hardcoding check the story book

2024-09-01 10:58 UTC, send2alamelu commented on react/src/CallsToAction/CopyLink/CopyLink.js
> +        leftIcon={leftIcon}
> TODO in upcoming: Add copy icon in right icon

2024-09-08 10:44 UTC, send2alamelu approved these changes

2024-09-08 10:44 UTC, merged