feat(communications): add status dot component
web-slate/TwixtUI pull request #85
Opened 2024-09-03 17:09 UTC by govindarajkp

![image](https://github.com/user-attachments/assets/c45b47c9-1073-4e26-8e42-5e31fe9a1f86)
![image](https://github.com/user-attachments/assets/1af89828-0ec2-4cea-aebb-657e21e98447)
![image](https://github.com/user-attachments/assets/1201dbe6-d7b2-4898-b98d-8a0f9b8fa0fb)

2024-09-05 13:11 UTC, prvn-mhsh commented
Why same SS??

2024-09-06 02:15 UTC, govindarajkp commented
SS mean?

2024-09-06 05:17 UTC, yuvarajuv approved these changes

2024-09-07 13:56 UTC, govindarajkp commented
![image](https://github.com/user-attachments/assets/dfa37055-40fd-4825-a228-5e9bb363da7d)
![image](https://github.com/user-attachments/assets/4cdde2da-9579-454d-b9eb-4ac83561c9da)
![image](https://github.com/user-attachments/assets/560b9781-a997-4429-9325-02a9f54dcb69)
![image](https://github.com/user-attachments/assets/39d86dcd-0f78-4f7b-9386-ecf6b469a6d8)
![image](https://github.com/user-attachments/assets/4c99e2d9-7c13-4edc-9e5b-8b0f32bede11)

![image](https://github.com/user-attachments/assets/48832db9-62cf-4b0e-8169-1ebec390869e)

2024-09-07 14:32 UTC, adhiththiyan commented on react/src/Communications/StatusDot/StatusDot.js
> +};
status value should be lowercase

2024-09-07 14:42 UTC, adhiththiyan commented on react/src/Communications/StatusDot/StatusDot.js
> +  return <span class={statsClasses}></span>;
Use <BoxItem type="inline">  component  from container group instead of span

2024-09-07 14:54 UTC, govindarajkp commented on react/src/Communications/StatusDot/StatusDot.js
> +};
default is the keyword in js , I can't keep the default in small case

2024-09-07 14:55 UTC, govindarajkp commented on react/src/Communications/StatusDot/StatusDot.js
> +  return <span class={statsClasses}></span>;
we do have 
![image](https://github.com/user-attachments/assets/c24de796-f790-414e-8f8b-deab538bbd73)

which one to use

2024-09-07 14:56 UTC, ramsunvtech commented on react/src/Communications/StatusDot/StatusDot.js
> +  return <span class={statsClasses}></span>;
TwixtBoxItem

2024-09-07 14:58 UTC, ramsunvtech requested changes

2024-09-07 14:58 UTC, ramsunvtech commented on react/src/Communications/StatusDot/StatusDot.js
> +};
you can keep default as empty / else case as well

2024-09-07 16:08 UTC, merged