feat(communications): add no data block component
web-slate/TwixtUI pull request #93
Opened 2024-09-10 02:35 UTC by govindarajkp

![image](https://github.com/user-attachments/assets/bb0298ca-3199-4164-a05a-a991bfb109d2)

2024-09-10 14:04 UTC, send2alamelu requested changes

2024-09-10 14:04 UTC, send2alamelu commented on react/src/Communications/NoDataBlock/NoDataBlock.js
> +      <svg version="1.1" viewBox="0 0 1340 1288" width={overwriteWidth} height={overwriteHeight} xmlns="http://www.w3.org/2000/svg">
this SVG doesn't look good, can we try from clip art?

2024-09-10 14:04 UTC, send2alamelu commented on react-examples/stories/Communications/NoDataBlock.stories.js
> +
can we have 2 -3 variations? adding additional TwixtButton as a children

For example:

1. When there is Job Opening List is empty and we use this no data block but we need to add button to refine search like "Clear Filter (secondary), Search Again (Primary)"

2024-09-16 03:41 UTC, govindarajkp commented
![image](https://github.com/user-attachments/assets/b3843322-ec9c-4964-a0d0-e839e48b2087)
![image](https://github.com/user-attachments/assets/af5c4ea1-0ecd-44cf-bb0e-0f9950ec9b1e)

Added Two type of images

2024-09-19 04:57 UTC, govindarajkp commented
![image](https://github.com/user-attachments/assets/e5f6e682-299a-480e-8c5d-4be1803e937c)

2024-10-01 14:17 UTC, closed without merging